### ISSUE TITLE
bcrypt-nodejs is no longer actively maintained

### ISSUE THREAD

**Issue by tchernobyl** [hookTracker/TimeTrackerServer#5]
> bcrypt-nodejs is no longer actively maintained. Please use bcrypt or bcryptjs. See https://github.com/kelektiv/node.bcrypt.js/wiki/bcrypt-vs-brypt.js to learn more about these two options

Ghaith  il y a 6 jours
I'll have a deep look :sourire: thanks , we'll be using bcrypt for passwords hashing ?

Mohamed Abderrazak  il y a 6 jours
le package utiliser pour le moment est

Mohamed Abderrazak  il y a 6 jours
bcrypt-nodejs

Mohamed Abderrazak  il y a 6 jours
et il est plus maintenu par l'auteur

Ghaith  il y a 6 jours
D'accord :sourire: bien noté

Mohamed Abderrazak  il y a 6 jours
du coup vaut mieux utiliser bcrypt ou bcrpyt.js
:+1:
1

**Comment by helios58** [comment]
Resolved in dev branch
